### ISSUE TITLE
database erzeugt sich jedes mal neu

### ISSUE THREAD

**Issue by Omega236** [x-jokay/docker-ccu-historian#3]
Hallo,
ich habe noch nicht soviel erfahrung, deshalb bitte nachsicht falls ich was falsch mache.
ich habe die 4 Enviroment Variablen hinzugefügt und die Zwei Volumes gebunden.
im Log bekomme ich:

`/usr/local/bin/docker-entrypoint.sh: 8: /usr/local/bin/docker-entrypoint.sh: [[: not found
2019-06-24 17:31:15|INFO   |CCU-Historian V2.1.0
2019-06-24 17:31:16|INFO   |(C)MDZ (info@ccu-historian.de)
2019-06-24 17:31:16|SEVERE |Exception: Can't access configuration file /opt/ccu-historian/config/ccu-historian.config
2019-06-24 17:31:16|SEVERE |Detail: java.lang.Exception: Can't access configuration file /opt/ccu-historian/config/ccu-historian.config
	at mdz.ccuhistorian.Configuration.isFileModified(Configuration.groovy:100)
	at mdz.ccuhistorian.Main$_run_closure3.doCall(Main.groovy:73)
	at mdz.ccuhistorian.Main$_run_closure3.call(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:72)
	at mdz.ccuhistorian.Main.main(Main.groovy:47)`

Wenn ich das Config File manuell ablege

bekomme ich diesen log 
`2019-06-24 17:38:05|INFO   |Connecting to 192.168.0.109:8701
2019-06-24 17:38:05|INFO   |Starting historian
2019-06-24 17:38:05|INFO   |Starting web server
2019-06-24 17:38:06|INFO   |Web server port: 80
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.43252.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.35086.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.35085.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.35087.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.950.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.6625.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.6732.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.6718.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.32546.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.45813.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.45815.VALUE
2019-06-24 17:38:07|INFO   |Historian: Creating data point SysVar.45814.VALUE`

aber das database Verzeichnis bleibt leer und beim nächsten restart beginnt er eine neue Datenbank

**Comment by Omega236** [comment]
OK
natürlich ist der Pfad zur Datenbank in meinem Manuell erzeugtem Config File falsch.

aber warum wird die Config File nicht richtig erzeugt.

Nutze nun sacomedv/ccu-historian, der hat das Config File korrekt erzeugt (dadurch bin ich draufgekommen).

**Comment by x-jokay** [comment]
Hellu

Vielen Dank fürs Melden, ich konnte das Problem bei mir reproduzieren und beheben.

Bei `xjokay/ccu-historian:latest` ist es bereits gefixt und auch das nächste Release `2.2.0` wird dann den Fix beinhalten.
